version: '3'

services:
  api:
    build: ./api
    env_file: ./api/.env
    ports:
      - "8000:8000"

  ui:
    build: ./ui
    links:
      - api
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.21.4-alpine
    links:
      - ui
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
