data:
  image: busybox
  volumes:
    - /etc/letsencrypt
    - /etc/nginx
    - /app/env
    - /var/log/nginx
    - /app/log
  command: "true"

app:
  build: ./app
  stdin_open: true
  tty: true
  expose:
    - "8000"
  volumes:
    - ./app:/app
  volumes_from:
    - data
  command: "gunicorn -b 0.0.0.0:8000 --access-logfile /app/log/gunicorn_access.log --error-logfile /app/log/gunicorn_error.log invent:app"

nginx:
  build: ./nginx
  links:
    - app
  volumes_from:
    - data
  ports:
    - "80:80"

acme:
  image: xataz/letsencrypt
  env_file: acme/env
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - data
  command: "certonly --standalone --agree-tos -m ${ACME_EMAIL} -d ${ACME_DOMAIN}"

